### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by prodnet** [gsas7q7o/opencl-tezos-pwsearch#1]
I'd like to ask you something in private, how can I contact you?

**Comment by prodnet** [comment]
pls reply.

**Comment by gsas7q7o** [comment]
@prodnet Many apologies that I left you waiting, I haven't been following the issues here. Let me know your email address and I'll contact you. (And if I can, I'll delete the comment after you post it, in case you don't want your email address posted here permanently.)
